{% set name = "parquet-metadata" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/parquet-metadata-{{ version }}.tar.gz
  sha256: 9643276066f7d5d8a0984345eecc7e4f2e75e6f31d3a6c7e941450347b5701cf

build:
  entry_points:
    - parquet-metadata = parquet_metadata.parquet_metadata:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - pyarrow

test:
  imports:
    - parquet_metadata
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/cldellow/parquet-metadata
  summary: A tool to show metadata about a Parquet file
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
